# Basic Settings
title: "SmartCentsGuide"           # Your site title
description: "Master Your Money, Maximize Your Life"  # Short description of your site
author: "smartcentsguide"                 # Your name or brand name

# GitHub Pages Settings
# Use the name of your GitHub repository if the site is hosted in a subdirectory.
# Leave it blank if it’s hosted at the root (like https://username.github.io).
baseurl: "/smartcentsguide"    # Example: "/SmartCentsGuide" if hosted in a subdirectory
url: "https://juanito777tt.github.io"  # Full URL to your GitHub Pages site

# Theme Settings
theme: caymen                       # Replace 'minima' with the name of your theme if using a GitHub-supported theme
# remote_theme: jekyll/minima       # If using a remote theme, uncomment and set here

# Plugins (optional)
# GitHub Pages supports these plugins natively.
plugins:
  - jekyll-feed                      # Adds an RSS feed
  - jekyll-seo-tag                   # Helps with SEO metadata

# Build Settings
markdown: kramdown
highlighter: rouge                   # Syntax highlighter

# Additional Settings (optional)
# Customize these as needed based on your theme documentation.
permalink: pretty                    # URL format (like /post-title/)
paginate: 5                          # Number of posts per page

# Social Links (optional)
twitter_username: "smartcentsguide"
github_username: "juanito777tt"
linkedin_username: "yourLinkedInUsername"
