# Site settings
title: "SmartCentsGuide"               # Blog title
description: "Personal finance tips, budgeting advice, and investment strategies."
url: "https://juanito777tt.github.io"   # Your GitHub username and site URL
baseurl: ""                             # Leave empty unless using a subfolder (e.g., /myblog)

# Theme settings
theme: jekyll-theme-cayman              # Choose your theme (e.g., cayman, minimal, slate)

# Social links (replace with your own social media handles)
twitter_username: smartcentsguide       # Your Twitter handle (no capitals)
github_username: juanito777tt           # Your GitHub username

# Plugins for additional features
plugins:
  - jekyll-seo-tag                      # For SEO optimization
  - jekyll-sitemap                      # Generates a sitemap for search engines

# Build settings
exclude:
  - README.md                           # Optional: Exclude files like README if you don't want them in the public folder

# Google Analytics (optional, uncomment to use)
# google_analytics: UA-XXXXXXXX-X        # Replace with your Google Analytics tracking ID

# Permalinks (format for post URLs)
permalink: /2024/11/11/my-first-post/    # Creates URLs like /2024/11/11/my-first-post/

